### PR TITLE
Add long double build on Windows

### PR DESCRIPTION
**Pull request by egpbos**

### CODE REVIEW

**Comment by jakirkham** [comment]
I think we can't build long double on Windows unfortunately. @jschueller would know more though.

**Comment by jschueller** [comment]
yes, it's unsupported on vc9

**Comment by jakirkham** [comment]
I guess we could try to build it only with vc14. Thoughts?

**Comment by jschueller** [comment]
I also tried this, but I prefered consistency across packages so I let it go.

**Comment by jakirkham** [comment]
In light of this discussion, what are your thoughts on this @egpbos?

**Comment by egpbos** [comment]
I'd like to use this Conda package for https://github.com/egpbos/xtensor-fftw on Windows too, as I'm currently doing for my Linux and macOS builds. Since I aim for feature completeness (i.e. including long double precision), I had to switch to using the prebuilt libraries from the FFTW website in my Windows build. For me, any way to get the long double library in this Conda package would be preferable to not having it :)

In any case, I see that the build is successful using miniconda36, but fails for miniconda27, any idea why this might be?

**Comment by jschueller** [comment]
yes, python27 requires vc9 runtime, which in turn does not support compiling fftw in long double precision

**Comment by egpbos** [comment]
Ok, well, I don't necessarily need Python 2.7 support at this point, so perhaps we could skip that for now?

**Comment by egpbos** [comment]
I've come to the conclusion that using long double this way is not that useful. The "official" pre-built FFTW Windows libraries use MinGW to build, which allows for a 12 byte long double. Using Visual Studio, this is not possible, since there long double is simply an alias for double, so 8 bytes. This means that a long double FFTW library compiled from Visual Studio is exactly the same as the double precision one, so it would be useless to include. The only thing that would make some sense is to build the long double library with MinGW, but that library would then only be useful for MinGW users.

I adapted xtensor-fftw to simply skip the long double tests in Windows.

Thanks for your feedback!

**Pull request closed without merging**
