### PR TITLE
update configure flags to enable -fPIC and AVX

### PR DESCRIPTION
**Pull request by grlee77**
I propose to add the `--with-pic` flag to `./configure` so that it will then be possible to build a version of pyFFTW that statically links to the FFTW libraries built here.  Currently when both MKL and pyFFTW are installed there is a problem where MKL FFT routines get dynamically linked instead of the desired FFTW ones.  This occurs, for instance, whenever numpy is imported prior to pyFFTW.  This has been causing a lot of pains for myself and others as discussed in the following places:
pyFFTW/pyFFTW#40
pyFFTW/pyFFTW#106
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/zXT3dRsKK10
It wouldn't be so bad except that the MKL routines only support a subset of the FFTW functionality.

I have created a version of the pyFFTW feedstock that resolves the issues above (if built against FFTW using the `--with-pic` flag):
https://github.com/grlee77/pyfftw-feedstock/tree/static_link
This is currently being done by patching setup.py to enable linking to the static libraries.

The second commit here just adds `--enable-avx` during configure to improve performance on machines that support AVX.  According the FFTW docs this does not **require** machines to have AVX, only that the compiler supports it at build time.

### CODE REVIEW

**Comment by jakirkham** [comment]
Interesting. Unfortunately, I don't have time to look at this week. Will take a closer look at it next week. Let's hold off on this until then.

**Comment by grlee77** [comment]
no problem. 

he following is a simple test that fails for me using the current FFTW and pyFFTW packages from conda-forge.  see explanations in the comments to the code

```python
import numpy as np  # MKL FFT symbols get loaded here
from pyfftw.interfaces.numpy_fft import fftn   # pyFFTW symbols won't replace the already loaded MKL ones
r = np.random.randn(32, 32, 32)
fftn(r, axes=(0, ))  # MKL cannot transform only 1 axis of a 3D array so pyFFTW will raise a RuntimeError due to a Null plan.
```

It seems the only simple solution to this with the current packages is to use `nomkl` to avoid MKL.  Ideally one would be able to use both pyFFTW and still have MKL for BLAS/LAPACK, though.  That is what I mainly want to address.

**Comment by grlee77** [comment]
Actually, the current packages seem to work fine on osx.  I only get the MKL symbol problem mentioned above on linux.

**Comment by grlee77** [comment]
ping @jakirkham 
any chance you will be able to take a look later this week?  I put a simple linux test case above that should fail on linux when installing FFTW & pyFFTW  from conda-forge alongside numpy with MKL.

The simplest workaround is to just use OpenBLAS numpy, but ideally the package should be compatible with MKL numpy as well.

I prefer to use MKL numpy/scipy from anaconda defaults at the moment, because I developed some Cython code that cimports `sgesvd` from `scipy.linalg.cython_lapack` and this runs much faster with the MKL `scipy` variant.  However, I also need to run FFTs over only subsets of the axes of n-dimensional arrays as in the example above!  This was the only solution I found so far to do both.

**Comment by jakirkham** [comment]
Sorry @grlee77 I have not forgotten about this. There just have been a few mission critical problems that needed sorting out of late.

Your proposal here seems reasonable, but I feel I have done a poor job on my initial formulation of this recipe. We should really try to have a for loop that gathers these 3 cases together. I'm worried that they have diverged a bit now and that has caused you difficulties and will soon cause others difficulties too. We should try and consolidate this if we can.

**Comment by grlee77** [comment]
updated to use a loop over the build cases.  is this what you had in mind?

**Comment by grlee77** [comment]
Perhaps `--enable-sse` should still be there along with `--enable-sse2` in the single precision case to support older cpus?

According to the [docs](http://www.fftw.org/fftw3_doc/Installation-on-Unix.html#Installation-on-Unix), --enable-sse, --enable-neon, --enable-altivec are only available for single precision.

--enable-sse2 and --enable-avx are available for both single or double, but not long double

**Comment by jakirkham** [comment]
Not sure whether it is worth it to worry about SSE2. I know that NumPy devs decided to drop SSE support. Still it is one flag and it should be easy to add it. So, yes, let's add it. Just saying that if we have problems down the road, I'm ok with dropping.

**Comment by jakirkham** [comment]
Not sure whether it is worth it to worry about SSE. I know that NumPy devs decided to drop SSE support. Still it is one flag and it should be easy to add it. So, yes, let's add it. Just saying that if we have problems down the road, I'm ok with dropping.

**Comment by grlee77** [comment]
I'm not sure if the --enable-sse2 and --enable-sse flags were redundant, but I don't think it hurts to add it.  the docs say "SSE2 works in both single and double precision (and is simply SSE in single precision)"

**Comment by jakirkham** [comment]
LGTM. @jjhelmus @alexbw, do either of you have thoughts on this?

It's pretty simple. We are enabling PIC and trying to use some of the nicer instruction sets (SSE, SSE2, AVX) to make things a bit faster. From my understanding FFTW will do a runtime check for these instructions and won't use them if they are not available. So, it isn't like they are hard-coded or anything.

**Comment by jakirkham** [comment]
Alright, as there have been no other comments for the last week, I'm going ahead with merging this. Thanks for putting this together @grlee77.

**Comment by jakirkham** [comment]
Weird. Running into a build failure on Linux due to Perl being missing? Could you please take a look, @grlee77?

**Comment by jakirkham** [comment]
Actually, we removed `perl` from the docker image so that is probably the cause. See this PR ( https://github.com/conda-forge/fftw-feedstock/pull/6 ) for a fix.

**Pull request merged**
