### PR TITLE
Build static library with fvisibility=hidden.

### PR DESCRIPTION
**Pull request by rainwoodman**
There were several reports of Anaconda's MKL interfering with extensions that links against fftw in unexpected ways.

https://github.com/pyFFTW/pyFFTW/issues/40
https://github.com/openjournals/joss-reviews/issues/1340

MKL runtime overrides `fftw*` dynamic symbols exported by the extension module. If the symbols in the .a archive are not marked as hidden, then they will be exported as dynamic symbols in the generated so file. Therefore with the current visibility setting even if a downstream extension links against the static version of the fftw library, MKL can still intervene and break the extensions.

With this PR, if a downstream extension links against the static fftw libraries, then MKL will not break them.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@jakirkham can you look at this one? It is related to an issue you commented on for pyFFTW

**Comment by beckermr** [comment]
This needs a rerender @rainwoodman.

**Comment by rainwoodman** [comment]
How do I do that? -- the rerender page is a broken link.

**Comment by grlee77** [comment]
@conda-forge-admin please rerender

**Comment by grlee77** [comment]
> How do I do that? -- the rerender page is a broken link. 

I just did it for you via the conda-forge-admin bot (see prior comment for future reference)

**Comment by grlee77** [comment]
I was not familiar with this flag, but the changes look reasonable to me based on the description and what little I read about it.

I can test it locally now with the existing pyFFTW recipe and make sure it is not going to cause any problems there.

**Comment by rainwoodman** [comment]
Thanks for the comment. I use a similar trick in pfft-python:

https://github.com/rainwoodman/pfft-python/blob/master/setup.py#L16

I will also test this on my local mpi4py-fft and let you know.

**Comment by grlee77** [comment]
I tested pyFFTW with this locally (on linux) and all seems well.

**Comment by beckermr** [comment]
Did you try with and without mkl?

**Comment by grlee77** [comment]
Yeah, I did test both ways. However, I think all of the tests were already passing prior to this change as well. I was unable to reproduce any MKL failures using a couple of examples from the issues cited above.

**Comment by grlee77** [comment]
Let's see how it goes for @rainwoodman mpi4py-fft because I think he just recently had the issue there with the existing build.

**Comment by rainwoodman** [comment]
I wonder what workaround pyfftw uses? There seems to be a lot of code in setup.py.

The only other fix I can think of is to notify the linker to only export the `init*` function of the module. But on this track, a fix will take a much longer time to propagate -- the initial authors of `distutils` decided not to support `export_symbols` argument on Unix, so we'll need to fix it there.

The symbolic binding workaround mentioned on the pyfftw thread seems to be very fragile and didn't work for me.

**Comment by rainwoodman** [comment]
I can confirm this and https://bitbucket.org/mpi4py/mpi4py-fft/pull-requests/7/prefer-using-a-libraries-to-hide-fftw/diff 

creates a mpi4py-fft that passes the fftw tests on a MKL enabled anaconda.

**Comment by rainwoodman** [comment]
Also, I wonder what @mingwandroid thinks about visibility settings of library archives?

**Comment by grlee77** [comment]
Given that this does not seem to break anything and resolves an issue for @rainwoodman, I am in favor of merging.

**Comment by mingwandroid** [comment]
I am in general in favour of hiding symbols.

> Given that this does not seem to break anything and resolves an issue 

Well, hiding symbols is going to break other things once this is released. One of those "publish and be damned" scenarios (though conda-build is learning about library exports used to help with this kind of thing in future).

**Comment by beckermr** [comment]
Whelp then let's ship this. Who wants to do the honors?

**Comment by grlee77** [comment]
Is there an easy way to see which downstream libraries depend on this and might need to be rebuilt due to the hidden symbols?
I know pyFFTW links to the static libs, but I'm not sure what other packages do.

**Comment by beckermr** [comment]
We can examine the dependent recipes in the conda forge bot graphs, but it won't say how those deps use the package (e.g. dynamic or static linking, etc.)

**Comment by mingwandroid** [comment]
> but it won't say how those deps use the package (e.g. dynamic or static linking, etc.)

I don't know anything about the bot graphs, but static vs dynamic can be determined (or guessed at pretty accurately) at the recipe level by whether the dep ends up in the run section or not (vs appearing in host or build only). This is because we mark static libs usage with `ignore_run_exports`.

**Comment by grlee77** [comment]
There are a few dozen dependencies, but as far as I can tell all of them except pyfftw include fftw in the runtime dependencies as well.

**Comment by beckermr** [comment]
They may not be doing that correctly. The deps are sometimes over linked.

**Comment by beckermr** [comment]
And sometimes people don't add the ignore run exports correctly.

**Comment by mingwandroid** [comment]
> And sometimes people don't add the ignore run exports correctly.

Then that is an error that conda-build will detect and report, so long as you use --error-overlinking and --error-overdepending.

**Comment by beckermr** [comment]
Ahhh cool. I am not sure CF uses those yet.

**Pull request merged**
