### PR TITLE
ENH added openmp for mac and linux

### LINKED ISSUE #20: OpenMP support
Is there a way to install through Conda for a build with OpenMP support? I'm using a project that needs libfftw3_omp.

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #20

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge/fftw This PR is ready to go. 

I am disabling the openmp libs for mac toolchain builds and windows systems. I am not claiming this solution is perfect, but it does get most of the way there. If someone knows the incantations for openmp on windows, I am happy to add it. However, my own experience building software for windows is very limited.

**Comment by beckermr** [comment]
Also, it appears `--with-combined-threads` is used for the windows builds which would preclude using both `pthreads` and `openmp`. Thus not shipping `openmp` for windows seems ok.

**Comment by beckermr** [comment]
Postscript: Upon reading more, I learned (and I guess y'all already knew) that you have to use `--with-combined-threads` for windows builds. Thus this PR is exactly what is possible for openmp.

**Comment by grlee77** [comment]
This looks pretty good to me. 

One side effect of this is that future pyFFTW builds would default to using OpenMP instead of pthreads unless we explicitly add an `PYFFTW_USE_PTHREADS` environment variable to the build script (as of release 0.11 of pyFFTW, OpenMP builds are selected by default over pthreads when both variants are present). 

I will leave it open a little longer to see if there is other feedback.

**Comment by beckermr** [comment]
Ahh goog point. We might want to force pthreads there since the toolchain build of that repo will then be different from the gcc7 builds for mac. IDK if we care...

**Comment by jakirkham** [comment]
The main issue with using OpenMP is one of the most popular implementations (GCC's OpenMP, a.k.a GOMP) is not fork safe. Combined with the fact that Python's `multiprocessing` uses forking, this is a recipe for nasty crashes with little warning. Having had to debug this issue personally before, am generally reluctant to make use of OpenMP if there is another option (as is the case here with pthreads).

ref: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58378

**Comment by grlee77** [comment]
> Having had to debug this issue personally before, am generally reluctant to make use of OpenMP if there is another option (as is the case here with pthreads).

Right, but pthreads-based FFTW C libs will still be available. This PR just adds the OpenMP variant as well (in separate dynamic library files).  We can keep downstream packages using pthreads when necessary (e.g. define `PYFFTW_USE_PTHREADS` for pyFFTW).

**Comment by beckermr** [comment]
This is right. There are extra binaries in the conda packages for people who want to link code against them (me). The pthreads binaries are still there. 

Given what you are saying @jakirkham, it sounds like a PR forcing pthreads on pyFFTW is required for this one to be merged. 

I will do that today.

**Comment by grlee77** [comment]
Merging this would not immediately break pyFFTW, because on OS X/linux it is statically compiled against FFTW to get around an unrelated numpy+mkl_fft issue. It would potentially cause a problem the next time we go to rebuild/update the pyFFTW recipe, though, so a PR there would be welcome.

**Comment by beckermr** [comment]
Done. https://github.com/conda-forge/pyfftw-feedstock/pull/29

**Comment by beckermr** [comment]
Alright @grlee77. I think we are good to go here too?

**Comment by grlee77** [comment]
Ready on my end.  Are you okay with this change now @jakirkham ?

**Comment by jakirkham** [comment]
Sure, there may be other libraries in the stack we need to watch out for. However as there is a nice clean separation between OpenMP-based and pthreads-based FFTW builds, this seems pretty reasonable.

**Pull request merged**
