### PR TITLE
Bump to 3.3.9

### PR DESCRIPTION
**Pull request by h-vetinari**
Trying to bump to [3.3.9](https://github.com/FFTW/fftw3/tags).

### CODE REVIEW

**Comment by h-vetinari** [comment]
Just saw that ms-mpi support was [recently](https://github.com/conda-forge/mpi-feedstock/pull/7) merged to the mpi meta-package. I guess we should try building for ms-mpi here? @conda-forge/msmpi @leofang

**Comment by h-vetinari** [comment]
Just wondering @conda-forge/fftw, shouldn't this package be `noarch: python`? It's only a test dependency...

**Comment by leofang** [comment]
Yeah give it a try and see how it goes? I have 0 experience with the Windows compiler toolchain, though, so I don't think I can offer any real help other than subscribing this PR 😂

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
> Just saw that ms-mpi support was [recently](https://github.com/conda-forge/mpi-feedstock/pull/7) merged to the mpi meta-package. I guess we should try building for ms-mpi here?

Do you want to try that here or in a separate PR?

**Comment by h-vetinari** [comment]
> Do you want to try that here or in a separate PR?

I'd say that's more suited for a separate PR. No need to hold up the version bump for that.

**Pull request merged**
