### PR TITLE
[DO NOT MERGE, FOR DISCUSSION ONLY] Add Windows (mingw-w64) build

### PR DESCRIPTION
**Pull request by mingwandroid**
I want to see if AppVeyor works on this.

### CODE REVIEW

**Comment by hadim** [comment]
Did you find a way to get it to work ?

**Comment by mingwandroid** [comment]
It seems not. @jakirkham, is it not possible to re-enable AppVeyor and have it run in the same PR?

**Comment by ocefpaf** [comment]
@mingwandroid I do not see the `appveyor.yml` file. It should be created with a re-render after you removed the Windows skip part. Can you try re-rendering ti again?

**Comment by mingwandroid** [comment]
Let's not rule out PEBCAK, seem I forgot to add `appveyor.yml`.

**Comment by jakirkham** [comment]
Yep, whenever changing `skip` one needs to re-render.

**Comment by jakirkham** [comment]
So it passes, but I don't think it actually worked. Looks like linking errors maybe? 😕

**Comment by hadim** [comment]
There is a bunch of undefined reference during tests for the AppVeyor build. Did you pass the tests @mingwandroid locally on Windows ?

**Comment by hadim** [comment]
I confirm the error locally on Windows 10. But I have no idea how to fix that...

**Comment by jakirkham** [comment]
Windows support was added some time ago in PR ( https://github.com/conda-forge/fftw-feedstock/pull/32 ) and refined to use upstream's CMake support in PR ( https://github.com/conda-forge/fftw-feedstock/pull/36 ). As such, will close this out. If there is interest in reviving this PR and exploring this direction, it would be best to start in a new PR as things have evolved substantially since this was created. Thanks for the interest, discussion, and work, which got Windows builds going here. :)

**Pull request closed without merging**
