### PR TITLE
Add Windows recipe

### PR DESCRIPTION
**Pull request by shadowwalkersb**
This recipe was adapted from [salilab/conda-recipes](https://github.com/salilab/conda-recipes), [bld.bat](https://github.com/salilab/conda-recipes/blob/master/fftw/bld.bat). I have no idea how to give credit or if it is necessary.

### CODE REVIEW

**Comment by jakirkham** [comment]
Yeah, I have seen a similar strategy used by [menpo]( https://github.com/menpo/ ). We prefer to build from source if possible. Let's see if our Windows gurus have any advice in issue ( https://github.com/conda-forge/fftw-feedstock/issues/2 ) and then proceed from there.

**Comment by jakirkham** [comment]
Please rebase/merge with `master`. This should hopefully cutdown some noise in the diff.

**Comment by shadowwalkersb** [comment]
Should we close this if it is not of interest?

**Comment by hadim** [comment]
Is this going to be merged ? Or do you prefer the version that does the build https://github.com/conda-forge/fftw-feedstock/pull/17 ?

Having a Windows build of fftw would be really nice !

**Comment by hadim** [comment]
Could we go ahead with this recipe ?  so we have a working package waiting for someone building it from source on appveyor. That sounds like an ok temporary solution. 

Thought ? 

@jakirkham

**Comment by jakirkham** [comment]
A Windows build has been added using CMake in PR ( https://github.com/conda-forge/fftw-feedstock/pull/32 ), which supersedes this. So am closing this out.

**Pull request closed without merging**
