### PR TITLE
Update to 3.3.5

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jakirkham** [comment]
LGTM. Any other thoughts?

**Comment by jjhelmus** [comment]
LGTM also, merging.

**Comment by jakirkham** [comment]
Also would be happy to have you on board if you wish to be a maintainer, @jschueller . 😉

**Comment by jschueller** [comment]
@jakirkham https://github.com/conda-forge/fftw-feedstock/pull/15

**Pull request merged**
